name: playground_monorepo

packages:
  - apps/**
  - packages/**

# Safer bootstrap to avoid Flutter startup lock
command:
  bootstrap:
    runPubGetInParallel: false
    usePubspecOverrides: false
#
# -----------------------------------------------------------------------------------------------------
scripts:
  # ---------------------------------------------------------------------------------------------------
  #
  #
  release: melos version
  bootstrap: melos bootstrap
  loc:report: bash scripts/loc_report.sh

  # ---------------------------------------------------------------------------------------------------

  # ---------- Maintenance ----------
  #
  clean: melos exec --concurrency=1 -- "flutter clean"
  clean:deep: melos exec --concurrency=1 -- "git clean -xfd -e .idea -e .vscode" # CAREFUL: nukes untracked files
  #
  pub:get: melos exec --concurrency=1 -- "flutter pub get"
  pub:get:shared_layers: melos exec --scope="shared_layers" --concurrency=1 -- "flutter pub get"
  pub:get:shared_core_modules: melos exec --scope="shared_core_modules" --concurrency=1 -- "flutter pub get"
  pub:upgrade: melos exec --concurrency=1 -- "flutter pub upgrade"
  pub:outdated: melos exec --concurrency=1 -- "flutter pub outdated"
  pub:deps: melos exec --concurrency=1 -- "flutter pub deps --style=compact"
  pub:cache:repair: melos exec --scope="*" --concurrency=1 -- "flutter pub cache repair"
  doctor: melos exec --concurrency=1 -- "flutter doctor -v"

  # ---------- Workspace checks ----------
  check: melos run format:check && melos run analyze && melos run test
  ci: melos run check

  # ---------------------------------------------------------------------------------------------------

  # ---------- Dart Code Metrics (global-DCM) ----------
  # to init - run "dart pub global activate dart_code_metrics
  dcm: melos exec -- "dart pub global run dart_code_metrics:metrics analyze lib --disable-sunset-warning --exclude='{/**.g.dart,/**.freezed.dart}'"
  dcm:html: melos exec -- "dart pub global run dart_code_metrics:metrics analyze lib --reporter=html --output-directory=build/dcm --disable-sunset-warning --exclude='{/**.g.dart,/**.freezed.dart}' && (open build/dcm/index.html || xdg-open build/dcm/index.html || start build\\dcm\\index.html)"
  dcm:changed: melos exec --since -- "dart pub global run dart_code_metrics:metrics analyze lib --disable-sunset-warning --exclude='{/**.g.dart,/**.freezed.dart}'"
  #
  # Through apps/packages:
  dcm:apps: melos exec --scope="*_on_*" -- "dart pub global run dart_code_metrics:metrics analyze lib --disable-sunset-warning --exclude='{/**.g.dart,/**.freezed.dart}'"
  dcm:packages: melos exec --scope="shared_*,adapters_*,features_*,app_bootstrap" -- "dart pub global run dart_code_metrics:metrics analyze lib --disable-sunset-warning --exclude='{/**.g.dart,/**.freezed.dart}'"

  # ---------------------------------------------------------------------------------------------------

  # ---------- VeryGood CLI Commands ----------
  # Create a new Flutter app or package
  # Usage: melos run create app --my_new_app (or pkg --my_new_package)
  create:
    run: bash scripts/vgv_cli/create.sh $MELOS_SCRIPT_EXTRA_ARGS
    description: Create Flutter app or package (use 'app' or 'pkg' as first arg)

  # ---------------------------------------------------------------------------------------------------

  # ---------- Lints & format ----------
  #
  fix:dry: melos exec -- "dart fix --dry-run"
  fix:apply: melos exec -- "dart fix --apply"

  # Write formats code in-place (never fails)
  format:write: melos exec -- "dart format ."
  # CI check (fails if formatting is needed)
  format:check: melos exec -- "dart format --output=none --set-exit-if-changed ."
  # Optional quick fix across all packages
  format:fix: melos exec -- "dart format --fix ."
  #
  # Analyzer (choose one)
  # analyze: melos exec -- "dart analyze --fatal-infos"   # strict (fails on infos)
  analyze: melos exec --fail-fast -- "flutter analyze" # pragmatic (fails on errors)

  # ---------------------------------------------------------------------------------------------------

  # ---------- Tests ----------
  #
  # Run tests for all packages and apps
  test: bash scripts/tests/run_tests.sh all
  test:apps: bash scripts/tests/run_tests.sh apps
  test:packages: bash scripts/tests/run_tests.sh packages
  #
  # Run tests for specific apps
  test:cubit: bash scripts/tests/run_tests.sh cubit
  test:riverpod: bash scripts/tests/run_tests.sh riverpod
  #
  # VeryGood test (with coverage and randomization)
  vg:test: melos exec --concurrency=1 -- "very_good test --coverage --test-randomize-ordering-seed random"
  #
  # ------ Coverage (generates HTML reports) -------
  #
  coverage: bash scripts/tests/run_coverage.sh all
  coverage:cubit: bash scripts/tests/run_coverage.sh cubit
  coverage:riverpod: bash scripts/tests/run_coverage.sh riverpod

  # ---------------------------------------------------------------------------------------------------
  # GEN
  # ---------------------------------------------------------------------------------------------------

  # ----------- App icons generation ------------
  #
  icons:gen: bash scripts/gen_code/gen_icons.sh all all
  icons:gen:cubit: bash scripts/gen_code/gen_icons.sh cubit all
  icons:gen:riverpod: bash scripts/gen_code/gen_icons.sh riverpod all
  icons:gen:dev: bash scripts/gen_code/gen_icons.sh all dev
  icons:gen:stg: bash scripts/gen_code/gen_icons.sh all stg
  #

  #
  # ---------- Codegen (build_runner) ----------
  #
  gen: bash scripts/gen_code/gen_codegen.sh all
  gen:adapters: bash scripts/gen_code/gen_codegen.sh adapters
  gen:packages: bash scripts/gen_code/gen_codegen.sh packages
  gen:apps: bash scripts/gen_code/gen_codegen.sh apps
  #
  gen:clean: |
    melos exec --scope="adapters_for_riverpod" --concurrency=1 -- dart run build_runner clean || true
    melos exec --scope="features_dd_layers" --concurrency=1 -- dart run build_runner clean || true
    melos exec --scope="shared_layers" --concurrency=1 -- dart run build_runner clean || true
    melos exec --scope="shared_core_modules" --concurrency=1 -- dart run build_runner clean || true
    melos exec --scope="app_on_riverpod" --concurrency=1 -- dart run build_runner clean || true
    melos exec --scope="app_on_cubit" --concurrency=1 -- dart run build_runner clean || true
  #
  # ---------- Watch (build_runner) ----------
  watch:adapters: melos exec --scope="adapters_for_riverpod" --concurrency=1 -- dart run build_runner watch --delete-conflicting-outputs
  watch:packages: |
    melos exec --scope="features_dd_layers" --concurrency=1 -- dart run build_runner watch --delete-conflicting-outputs
    melos exec --scope="shared_layers" --concurrency=1 -- dart run build_runner watch --delete-conflicting-outputs
    melos exec --scope="shared_core_modules" --concurrency=1 -- dart run build_runner watch --delete-conflicting-outputs
  watch:apps: |
    melos exec --scope="app_on_riverpod" --concurrency=1 -- dart run build_runner watch --delete-conflicting-outputs
    melos exec --scope="app_on_cubit" --concurrency=1 -- dart run build_runner watch --delete-conflicting-outputs
  #
  #
  #--------- Localization code generation (Dual-Layer: Core + App) ----------
  #
  localization:gen:core: bash scripts/gen_code/gen_localization.sh core
  localization:gen:cubit: bash scripts/gen_code/gen_localization.sh cubit
  localization:gen:riverpod: bash scripts/gen_code/gen_localization.sh riverpod
  localization:gen:apps: bash scripts/gen_code/gen_localization.sh apps
  localization:gen:all: bash scripts/gen_code/gen_localization.sh all
  locale:regen: bash scripts/gen_code/gen_localization.sh all
  #

  #
  # ---------- Spider (assets paths) ----------
  #
  spider:activate: dart pub global activate spider // one-time action
  #
  spider:gen: bash scripts/gen_code/gen_spider.sh all all
  spider:gen:cubit: bash scripts/gen_code/gen_spider.sh cubit all
  spider:gen:riverpod: bash scripts/gen_code/gen_spider.sh riverpod all
  spider:gen:images: bash scripts/gen_code/gen_spider.sh all images
  spider:gen:icons: bash scripts/gen_code/gen_spider.sh all icons
  #
  spider:apps:gen: bash scripts/gen_code/gen_spider.sh all all
  #

  #
  # ---------- XCode Troubleshooting ----------
  #
  # See scripts/xcode_troubleshooting/ for implementation details
  #
  # Kill all xcodebuild processes (fixes concurrent build errors)
  kill:xcode: bash scripts/xcode_troubleshooting/kill_xcode.sh
  #
  # Clean iOS build artifacts for a specific app
  clean:ios:state_symmetric_on_riverpod: bash scripts/xcode_troubleshooting/clean_ios.sh riverpod
  clean:ios:state_symmetric_on_cubit: bash scripts/xcode_troubleshooting/clean_ios.sh cubit
  #
  # Reset iOS build completely (clean + remove DerivedData)
  reset:ios:state_symmetric_on_riverpod: bash scripts/xcode_troubleshooting/reset_ios.sh riverpod
  reset:ios:state_symmetric_on_cubit: bash scripts/xcode_troubleshooting/reset_ios.sh cubit
  #
  # Quick fix for "concurrent builds" error (kill + clean current directory)
  fix:ios: bash scripts/xcode_troubleshooting/fix_ios.sh
