name: monorepo

packages:
  - apps/**
  - packages/**

# Safer bootstrap to avoid Flutter startup lock
command:
  bootstrap:
    runPubGetInParallel: false
    usePubspecOverrides: true

scripts:
  # ---------- Maintenance ----------
  clean: melos exec --concurrency=1 -- "flutter clean"
  clean:deep: melos exec --concurrency=1 -- "git clean -xfd -e .idea -e .vscode" # CAREFUL: nukes untracked files

  bootstrap: melos bootstrap

  pub:get: melos exec --concurrency=1 -- "flutter pub get"
  pub:get:core: melos exec --scope="core" --concurrency=1 -- "flutter pub get"
  pub:upgrade: melos exec --concurrency=1 -- "flutter pub upgrade"
  pub:outdated: melos exec --concurrency=1 -- "flutter pub outdated"
  pub:deps: melos exec --concurrency=1 -- "flutter pub deps --style=compact"
  pub:cache:repair: melos exec --scope="*" --concurrency=1 -- "flutter pub cache repair"
  doctor: melos exec --concurrency=1 -- "flutter doctor -v"

  # ---------- Codegen (only where it's needed) ----------
  gen: melos exec --fail-fast --depends-on build_runner -- "dart run build_runner build --delete-conflicting-outputs"
  gen:watch: melos exec --fail-fast --depends-on build_runner -- "dart run build_runner watch --delete-conflicting-outputs"
  gen:clean: melos exec --depends-on build_runner -- "dart run build_runner clean"

  # ---------- Lints & format ----------
  fix:dry: melos exec -- "dart fix --dry-run"
  fix:apply: melos exec -- "dart fix --apply"

  # Write formats code in-place (never fails)
  format:write: melos exec -- "dart format ."
  # CI check (fails if formatting is needed)
  format:check: melos exec -- "dart format --output=none --set-exit-if-changed ."
  # Optional quick fix across all packages
  format:fix: melos exec -- "dart format --fix ."

  # Analyzer (choose one)
  # analyze: melos exec -- "dart analyze --fatal-infos"   # strict (fails on infos)
  analyze: melos exec --fail-fast -- "flutter analyze" # pragmatic (fails on errors)

  # ---------- Tests ----------
  vg:test: melos exec --concurrency=1 -- "very_good test --coverage --test-randomize-ordering-seed random"
  test: melos exec -- "flutter test --no-pub --concurrency=4"
  coverage:
    melos exec --scope="app_on_*" -- "flutter test --coverage --no-pub"

    # ------ Coverage per app -------

  # --- Coverage per app (safe multiline) ---
  coverage:bloc: |
    melos exec --scope="app_on_bloc" --concurrency=1 -- \
      bash -lc 'flutter test --coverage --no-pub && genhtml coverage/lcov.info -o coverage/html && (open coverage/html/index.html || xdg-open coverage/html/index.html || start coverage\\html\\index.html)'

  coverage:riverpod: |
    melos exec --scope="app_on_riverpod" --concurrency=1 -- \
      bash -lc 'flutter test --coverage --no-pub && genhtml coverage/lcov.info -o coverage/html && (open coverage/html/index.html || xdg-open coverage/html/index.html || start coverage\\html\\index.html)'

  # ---------- Run (per app & flavor) ----------

  # ---------- Run (Blueprint on Riverpod) ----------
  run:rp:dev: melos exec --scope="blueprint_on_riverpod" --concurrency=1 -- "flutter run --flavor development -t lib/main_development.dart"
  run:rp:stg: melos exec --scope="blueprint_on_riverpod" --concurrency=1 -- "flutter run --flavor staging     -t lib/main_staging.dart"

  # ---------- Build (Blueprint on Riverpod) ----------
  build:rp:apk:dev: melos exec --scope="blueprint_on_riverpod" --concurrency=1 -- "flutter build apk       --flavor development -t lib/main_development.dart"
  build:rp:aab:stg: melos exec --scope="blueprint_on_riverpod" --concurrency=1 -- "flutter build appbundle --flavor staging     -t lib/main_staging.dart"

  # iOS ipa (коли буде підпис)
  build:ios:rp:dev: melos exec --scope="blueprint_on_riverpod" --concurrency=1 -- "flutter build ipa --flavor development -t lib/main_development.dart"
  build:ios:rp:stg: melos exec --scope="blueprint_on_riverpod" --concurrency=1 -- "flutter build ipa --flavor staging     -t lib/main_staging.dart"

  # ---------- Run blueprint_on_cubit ----------
  run:blueprint:dev:
    melos exec --scope="blueprint_on_cubit" --concurrency=1 -- \
    "flutter run --flavor development -t lib/main_development.dart"
  run:blueprint:stg:
    melos exec --scope="blueprint_on_cubit" --concurrency=1 -- \
    "flutter run --flavor staging -t lib/main_staging.dart"

  # ---------- Run blueprint_on_cubit (explicit entrypoint paths) ----------
  run:blueprint:main:dev:
    melos exec --scope="blueprint_on_cubit" --concurrency=1 -- \
    "flutter run -t apps/blueprint_on_cubit/lib/main_development.dart"
  run:blueprint:main:stg:
    melos exec --scope="blueprint_on_cubit" --concurrency=1 -- \
    "flutter run -t apps/blueprint_on_cubit/lib/main_staging.dart"

  # ---------- Build blueprint_on_cubit (Android) ----------
  build:blueprint:apk:dev:
    melos exec --scope="blueprint_on_cubit" --concurrency=1 -- \
    "flutter build apk --flavor development -t lib/main_development.dart"
  build:blueprint:apk:stg:
    melos exec --scope="blueprint_on_cubit" --concurrency=1 -- \
    "flutter build apk --flavor staging -t lib/main_staging.dart"

  build:blueprint:aab:stg:
    melos exec --scope="blueprint_on_cubit" --concurrency=1 -- \
    "flutter build appbundle --flavor staging -t lib/main_staging.dart"

  # ---------- Build blueprint_on_cubit (iOS) ----------
  build:ios:blueprint:dev:
    melos exec --scope="blueprint_on_cubit" --concurrency=1 -- \
    "flutter build ipa --flavor development -t lib/main_development.dart"
  build:ios:blueprint:stg:
    melos exec --scope="blueprint_on_cubit" --concurrency=1 -- \
    "flutter build ipa --flavor staging -t lib/main_staging.dart"

  # ---------- Run (direct entrypoint, без flavor) ----------
  run:bloc:main:dev: melos exec --scope="app_on_bloc" --concurrency=1 -- "flutter run -t apps/app_on_bloc/lib/main_development.dart"
  run:bloc:main:stg: melos exec --scope="app_on_bloc" --concurrency=1 -- "flutter run -t apps/app_on_bloc/lib/main_staging.dart"

  # ---------- Builds ----------
  build:bloc:apk:dev: melos exec --scope="app_on_bloc" --concurrency=1 -- "flutter build apk       --flavor development -t lib/main_development.dart"
  build:bloc:aab:prod: melos exec --scope="app_on_bloc" --concurrency=1 -- "flutter build appbundle --flavor production  -t lib/main_production.dart"

  build:riverpod:apk:dev: melos exec --scope="app_on_riverpod" --concurrency=1 -- "flutter build apk       --flavor development -t lib/main_development.dart"
  build:riverpod:aab:prod: melos exec --scope="app_on_riverpod" --concurrency=1 -- "flutter build appbundle --flavor production  -t lib/main_production.dart"

  # iOS (requires codesigning set up)
  build:ios:bloc:dev: melos exec --scope="app_on_bloc" --concurrency=1 -- "flutter build ipa --flavor development -t lib/main_development.dart"
  build:ios:riverpod:dev: melos exec --scope="app_on_riverpod" --concurrency=1 -- "flutter build ipa --flavor development -t lib/main_development.dart"

  # ---------- Workspace checks ----------
  check: melos run format:check && melos run analyze && melos run test
  ci: melos run check

  # ---------- Dart Code Metrics (global-DCM) ----------
  dcm: melos exec -- "dart pub global run dart_code_metrics:metrics analyze lib --disable-sunset-warning --exclude='{/**.g.dart,/**.freezed.dart}'"
  dcm:html: melos exec -- "dart pub global run dart_code_metrics:metrics analyze lib --reporter=html --output-directory=build/dcm --disable-sunset-warning --exclude='{/**.g.dart,/**.freezed.dart}' && (open build/dcm/index.html || xdg-open build/dcm/index.html || start build\\dcm\\index.html)"
  dcm:changed: melos exec --since -- "dart pub global run dart_code_metrics:metrics analyze lib --disable-sunset-warning --exclude='{/**.g.dart,/**.freezed.dart}'"

  # Through apps/packages:
  dcm:bloc: melos exec --scope="app_on_bloc" -- "dart pub global run dart_code_metrics:metrics analyze lib --exclude='{/**.g.dart,/**.freezed.dart}'"
  dcm:core: melos exec --scope="core" -- "dart pub global run dart_code_metrics:metrics analyze lib --disable-sunset-warning --exclude='{/**.g.dart,/**.freezed.dart}'"
  dcm:riverpod: melos exec --scope="app_on_riverpod" -- "dart pub global run dart_code_metrics:metrics analyze lib --disable-sunset-warning --exclude='{/**.g.dart,/**.freezed.dart}'"

  # ---------- Versioning (per-package releases if ever needed) ----------
  release: melos version

  # --- App icons (blueprint_on_cubit) ---
  icons:blueprint:dev:
    melos exec --scope="blueprint_on_cubit" --concurrency=1 -- \
    "flutter pub run flutter_launcher_icons -f pubspec_dev.yaml"

  icons:blueprint:stg:
    melos exec --scope="blueprint_on_cubit" --concurrency=1 -- \
    "flutter pub run flutter_launcher_icons -f pubspec_stg.yaml"

  icons:blueprint:all: |
    melos run icons:blueprint:dev
    melos run icons:blueprint:stg

  # --- App icons (blueprint_on_riverpod) ---
  icons:riverpod:dev:
    melos exec --scope="blueprint_on_riverpod" --concurrency=1 -- \
    "flutter pub run flutter_launcher_icons -f pubspec_dev.yaml"

  icons:riverpod:stg:
    melos exec --scope="blueprint_on_riverpod" --concurrency=1 -- \
    "flutter pub run flutter_launcher_icons -f pubspec_stg.yaml"

  icons:riverpod:all: |
    melos run icons:riverpod:dev
    melos run icons:riverpod:stg

  # --- One-shot for both apps & both flavors ---
  icons:all: |
    melos run icons:blueprint:dev
    melos run icons:blueprint:stg
    melos run icons:riverpod:dev
    melos run icons:riverpod:stg
