name: Documentation
description: Improve or add documentation
labels: [documentation]
body:
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: Affected package/module in the monorepo
      options:
        - features_dd_layers
        - shared_core_modules
        - shared_layers
        - shared_widgets
        - shared_utils
        - adapters_for_bloc
        - adapters_for_riverpod
        - adapters_for_firebase
        - app_bootstrap
        - app_on_cubit
        - app_on_riverpod
        - monorepo
        - ci/cd
        - docs
    validations:
      required: true

  - type: textarea
    id: change
    attributes:
      label: What to document?
      placeholder: |
        Update README in packages/core
        Add ADR for ...
    validations:
      required: true

  - type: checkboxes
    id: targets
    attributes:
      label: Targets
      options:
        - label: README
        - label: ADR
        - label: API docs
        - label: Developer guide
        - label: Contribution guide

  - type: textarea
    id: links
    attributes:
      label: Related links
      placeholder: Design doc / PR / issue links
