// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyC6OLRmlzRalTHKuwpVJSMePkQuQop-DQk',
//     appId: '1:215897575173:android:eee7a0a7f3dc7cca2fb16c',
//     messagingSenderId: '215897575173',
//     projectId: 'blueprint-on-bloc-dev',
//     storageBucket: 'blueprint-on-bloc-dev.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBG_dRMpvYn1Lq-kOkbVAiIv52aJ7iEJEo',
//     appId: '1:215897575173:ios:c74bd68f1869763c2fb16c',
//     messagingSenderId: '215897575173',
//     projectId: 'blueprint-on-bloc-dev',
//     storageBucket: 'blueprint-on-bloc-dev.firebasestorage.app',
//     iosBundleId: 'com.romangodun.blueprint-on-qubit.dev',
//   );
// }
